const ENTER_EVENT = 'ENTER_EVENT';
const DROP_EVENT = 'DROP_EVENT';
const ERROR_EVENT = 'ERROR_EVENT';
const ZOOM_EVENT = 'ZOOM_EVENT';
const SYNC_EVENT = 'SYNC_EVENT';
const MAGNET_EVENT = 'MAGNET_EVENT';
const PLAY_EVENT = 'PLAY_EVENT';
const QUESTION_EVENT = 'QUESTION_EVENT';
const LOGING_EVENT = 'LOGING_EVENT';

module.exports = {
    ENTER_EVENT,
    DROP_EVENT,
    ERROR_EVENT,
    SYNC_EVENT,
    ZOOM_EVENT,
    MAGNET_EVENT,
    PLAY_EVENT,
    QUESTION_EVENT,
    LOGING_EVENT
}