const ENTER_EVENT = 'ENTER_EVENT';
const ACCEPT_EVENT = 'ACCEPT_EVENT';
const ENTER_RETRY_EVENT = 'ENTER_RETRY_EVENT';
const ENTERED_EVENT = 'ENTERED_EVENT';
const REACTION_EVENT = 'REACTION_EVENT';
const CLEAR_COUNT_EVENT = 'CLEAR_COUNT_EVENT';
const LEAVE_EVENT = 'LEAVE_EVENT';
const LEFT_EVENT = 'LEFT_EVENT';
const ERROR_EVENT = 'ERROR_EVENT';

module.exports = {
    ENTER_EVENT,
    ACCEPT_EVENT,
    ENTER_RETRY_EVENT,
    ENTERED_EVENT,
    REACTION_EVENT,
    CLEAR_COUNT_EVENT,
    LEAVE_EVENT,
    LEFT_EVENT,
    ERROR_EVENT
};